services:
  postgres:
    image: postgres:17
    container_name: quizarena-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8
    container_name: quizarena-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: src/QuizArena.WebApi/Dockerfile
    container_name: quizarena-webapi
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "5000:8080"

volumes:
  postgres_data:
  mongo_data:
