using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuizArena.Persistence.Migrations.Identity
{
    // NOTE (see the review response): hand-written, not generated by `dotnet ef migrations add`, for the
    // same reason as App/20260821000000_AddOutboxAndGameHistoryGameId.cs — no dotnet SDK / no nuget.org
    // access in this sandbox. Please verify with `dotnet ef migrations add AddRefreshTokenFamilyId
    // --project QuizArena.Persistence --startup-project QuizArena.WebApi --context ApplicationIdentityDbContext`
    // before relying on it.
    /// <inheritdoc />
    public partial class AddRefreshTokenFamilyId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // S6: existing (pre-migration) tokens all get the same placeholder family. The only practical
            // effect is that if two *different* users' pre-existing sessions somehow both hit reuse
            // detection, they'd revoke a shared family instead of independent ones — vanishingly unlikely,
            // and self-correcting anyway since every session gets a real, unique FamilyId the next time it
            // refreshes.
            migrationBuilder.AddColumn<Guid>(
                name: "FamilyId",
                table: "RefreshTokens",
                type: "uuid",
                nullable: false,
                defaultValue: Guid.Empty);

            migrationBuilder.CreateIndex(
                name: "IX_RefreshTokens_FamilyId",
                table: "RefreshTokens",
                column: "FamilyId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_RefreshTokens_FamilyId",
                table: "RefreshTokens");

            migrationBuilder.DropColumn(
                name: "FamilyId",
                table: "RefreshTokens");
        }
    }
}
