using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuizArena.Persistence.Migrations.App
{
    // NOTE (see the review response): hand-written, not generated by `dotnet ef migrations add`, because
    // this sandbox has no dotnet SDK / no nuget.org access to run that command. Please regenerate or at
    // least verify this via `dotnet ef migrations add AddOutboxAndGameHistoryGameId --project
    // QuizArena.Persistence --startup-project QuizArena.WebApi` (it should come back a no-op diff if this
    // file already matches) before relying on it against a real database.
    /// <inheritdoc />
    public partial class AddOutboxAndGameHistoryGameId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // W7: existing rows get GameId = Guid.Empty as a harmless placeholder — they'll all collapse
            // into a single "game" for the dashboard's distinct-GameId count, which is a fair reflection of
            // reality (nothing about those rows told us which real game they belonged to; that information
            // simply didn't exist before this migration).
            migrationBuilder.AddColumn<Guid>(
                name: "GameId",
                table: "GameHistory",
                type: "uuid",
                nullable: false,
                defaultValue: Guid.Empty);

            migrationBuilder.CreateIndex(
                name: "IX_GameHistory_GameId",
                table: "GameHistory",
                column: "GameId");

            // W4: the transactional outbox table.
            migrationBuilder.CreateTable(
                name: "OutboxMessages",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Type = table.Column<string>(type: "character varying(400)", maxLength: 400, nullable: false),
                    Payload = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    NextAttemptAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    ProcessedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    RetryCount = table.Column<int>(type: "integer", nullable: false),
                    LastError = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OutboxMessages", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_OutboxMessages_ProcessedAt_NextAttemptAt",
                table: "OutboxMessages",
                columns: new[] { "ProcessedAt", "NextAttemptAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OutboxMessages");

            migrationBuilder.DropIndex(
                name: "IX_GameHistory_GameId",
                table: "GameHistory");

            migrationBuilder.DropColumn(
                name: "GameId",
                table: "GameHistory");
        }
    }
}
